repos:
  - repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.8
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
        files: ^pterasoftware/
  - repo: local
    hooks:
      - id: ascii-only
        name: ascii-only
        entry: python scripts/check_ascii_only.py
        language: system
        types: [text]
        exclude: '\.ui$'
      - id: mypy
        name: mypy
        entry: mypy pterasoftware
        language: system
        always_run: true
        pass_filenames: false
