name: codespell

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2
        continue-on-error: true
        with:
          ignore_words_file: .codespell-ignore.txt
          skip: "*/_build/*,*.dat"
